-- MySQL Script generated by MySQL Workbench
-- Wed Nov 15 16:41:06 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SCGR
-- -----------------------------------------------------
DROP DATABASE IF EXISTS `SCGR`;
-- -----------------------------------------------------
-- Schema SCGR
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SCGR` DEFAULT CHARACTER SET utf8 ;
USE `SCGR` ;

-- -----------------------------------------------------
-- Table `SCGR`.`atleta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCGR`.`atleta` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `apelido` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `sexo` TINYINT(1) NOT NULL,
  `tamanho_camisa` VARCHAR(2) NOT NULL,
  `data_nascimento` VARCHAR(10) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(6) NOT NULL,
  `complemento` VARCHAR(45) NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `celular` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCGR`.`organizador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCGR`.`organizador` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `sexo` VARCHAR(1) NOT NULL,
  `data_nascimento` VARCHAR(10) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(6) NOT NULL,
  `complemento` VARCHAR(45) NULL,
  `telefone` VARCHAR(11) NULL,
  `celular` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCGR`.`corrida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCGR`.`corrida` (
  `id` INT NOT NULL,
  `nome_corrida` VARCHAR(45) BINARY NOT NULL,
  `horario` VARCHAR(5) NOT NULL,
  `data` VARCHAR(8) NOT NULL,
  `max_pessoa` INT NOT NULL,
  `banner` VARCHAR(255) NULL,
  `descricao` VARCHAR(45) NULL,
  `regulamento` VARCHAR(255) NULL,
  `cep` VARCHAR(8) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `organizador_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_corridas_organizadores1_idx` (`organizador_id` ASC),
  CONSTRAINT `fk_corridas_organizadores1`
    FOREIGN KEY (`organizador_id`)
    REFERENCES `SCGR`.`organizador` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCGR`.`lote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCGR`.`lote` (
  `id` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `preco` DOUBLE NOT NULL,
  `data_inicio` VARCHAR(19) NOT NULL,
  `data_final` VARCHAR(19) NOT NULL,
  `quantidade` INT NOT NULL,
  `corrida_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ingressos_corridas1_idx` (`corrida_id` ASC),
  CONSTRAINT `fk_ingressos_corridas1`
    FOREIGN KEY (`corrida_id`)
    REFERENCES `SCGR`.`corrida` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCGR`.`percurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCGR`.`percurso` (
  `id` INT NOT NULL,
  `imagem_percurso` VARCHAR(255) NOT NULL,
  `quilometragem` DOUBLE NOT NULL,
  `corrida_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_percursos_corridas1_idx` (`corrida_id` ASC),
  CONSTRAINT `fk_percursos_corridas1`
    FOREIGN KEY (`corrida_id`)
    REFERENCES `SCGR`.`corrida` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCGR`.`cartao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCGR`.`cartao` (
  `id` INT NOT NULL,
  `numero` VARCHAR(16) NOT NULL,
  `codigo_seguranca` VARCHAR(3) NOT NULL,
  `validade` VARCHAR(5) NOT NULL,
  `nome_titular` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCGR`.`boleto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCGR`.`boleto` (
  `id` INT NOT NULL,
  `codigo_barra` VARCHAR(45) NOT NULL,
  `data_emissao` VARCHAR(10) NOT NULL,
  `data_vencimento` VARCHAR(10) NOT NULL,
  `nome_titular` VARCHAR(45) NOT NULL,
  `cpf_titular` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCGR`.`inscricao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCGR`.`inscricao` (
  `id` INT NOT NULL,
  `percursos_id` INT NOT NULL,
  `data_compra` VARCHAR(10) NOT NULL,
  `numero_peito` INT NOT NULL,
  `pago` TINYINT(1) NULL,
  `kit_retirado` TINYINT(1) NULL,
  `tempo_largada` VARCHAR(8) NULL,
  `tempo_chegada` VARCHAR(8) NULL,
  `atleta_id` INT NOT NULL,
  `cartao_id` INT NULL,
  `boleto_id` INT NULL,
  PRIMARY KEY (`id`, `percursos_id`),
  INDEX `fk_inscricao_atleta1_idx` (`atleta_id` ASC),
  INDEX `fk_inscricoes_percursos1_idx` (`percursos_id` ASC),
  INDEX `fk_inscricoes_cartao1_idx` (`cartao_id` ASC),
  INDEX `fk_inscricoes_boleto1_idx` (`boleto_id` ASC),
  CONSTRAINT `fk_inscricao_atleta1`
    FOREIGN KEY (`atleta_id`)
    REFERENCES `SCGR`.`atleta` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_inscricoes_percursos1`
    FOREIGN KEY (`percursos_id`)
    REFERENCES `SCGR`.`percurso` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_inscricoes_cartao1`
    FOREIGN KEY (`cartao_id`)
    REFERENCES `SCGR`.`cartao` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_inscricoes_boleto1`
    FOREIGN KEY (`boleto_id`)
    REFERENCES `SCGR`.`boleto` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCGR`.`kit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCGR`.`kit` (
  `id` INT NOT NULL,
  `corrida_id` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `imagem_kit` VARCHAR(255) NULL,
  `tipo_chip` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `corrida_id`),
  INDEX `fk_kits_corridas1_idx` (`corrida_id` ASC),
  CONSTRAINT `fk_kits_corridas1`
    FOREIGN KEY (`corrida_id`)
    REFERENCES `SCGR`.`corrida` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCGR`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCGR`.`administrador` (
  `id` INT NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCGR`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCGR`.`produto` (
  `id` INT NOT NULL,
  `nome` VARCHAR(80) NOT NULL,
  `administrador_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produto_administrador1_idx` (`administrador_id` ASC),
  CONSTRAINT `fk_produto_administrador1`
    FOREIGN KEY (`administrador_id`)
    REFERENCES `SCGR`.`administrador` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCGR`.`produto_kit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCGR`.`produto_kit` (
  `id` INT NOT NULL,
  `kit_id` INT NOT NULL,
  `descricao` VARCHAR(155) NOT NULL,
  `valor` DOUBLE(6,2) NOT NULL,
  `produto_id` INT NOT NULL,
  PRIMARY KEY (`id`, `kit_id`),
  INDEX `fk_produtos_kit_kits1_idx` (`kit_id` ASC),
  INDEX `fk_produtos_kit_produto1_idx` (`produto_id` ASC),
  CONSTRAINT `fk_produtos_kit_kits1`
    FOREIGN KEY (`kit_id`)
    REFERENCES `SCGR`.`kit` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_produtos_kit_produto1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `SCGR`.`produto` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCGR`.`ranking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCGR`.`ranking` (
  `id` INT NOT NULL,
  `nome_ranking` VARCHAR(45) NOT NULL,
  `administrador_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rankings_administrador1_idx` (`administrador_id` ASC),
  CONSTRAINT `fk_rankings_administrador1`
    FOREIGN KEY (`administrador_id`)
    REFERENCES `SCGR`.`administrador` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCGR`.`pontuacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCGR`.`pontuacao` (
  `id` INT NOT NULL,
  `rankings_id` INT NOT NULL,
  `pontuacao` INT NOT NULL,
  PRIMARY KEY (`id`, `rankings_id`),
  INDEX `fk_pontuacoes_rankings1_idx` (`rankings_id` ASC),
  CONSTRAINT `fk_pontuacoes_rankings1`
    FOREIGN KEY (`rankings_id`)
    REFERENCES `SCGR`.`ranking` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCGR`.`corrida_ranking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SCGR`.`corrida_ranking` (
  `id` INT NOT NULL,
  `corrida_id` INT NOT NULL,
  `ranking_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_corrida_ranking_corridas1_idx` (`corrida_id` ASC),
  INDEX `fk_corrida_ranking_rankings1_idx` (`ranking_id` ASC),
  CONSTRAINT `fk_corrida_ranking_corridas1`
    FOREIGN KEY (`corrida_id`)
    REFERENCES `SCGR`.`corrida` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_corrida_ranking_rankings1`
    FOREIGN KEY (`ranking_id`)
    REFERENCES `SCGR`.`ranking` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
