-- MySQL Script generated by MySQL Workbench
-- Wed Jan  3 15:22:22 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SGCR
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SGCR` ;

-- -----------------------------------------------------
-- Schema SGCR
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SGCR` DEFAULT CHARACTER SET utf8 ;
USE `SGCR` ;

-- -----------------------------------------------------
-- Table `SGCR`.`atleta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGCR`.`atleta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `apelido` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `sexo` VARCHAR(1) NOT NULL,
  `tamanho_camisa` VARCHAR(2) NOT NULL,
  `data_nascimento` VARCHAR(10) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `cep` VARCHAR(9) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `logradouro` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `complemento` VARCHAR(80) NULL,
  `telefone` VARCHAR(14) NOT NULL,
  `celular` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGCR`.`organizador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGCR`.`organizador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `sexo` VARCHAR(1) NOT NULL,
  `data_nascimento` VARCHAR(10) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `cep` VARCHAR(9) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `logradouro` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `complemento` VARCHAR(80) NULL,
  `telefone` VARCHAR(14) NULL,
  `celular` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGCR`.`corrida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGCR`.`corrida` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) BINARY NOT NULL,
  `horario` VARCHAR(8) NOT NULL,
  `data` VARCHAR(10) NOT NULL,
  `max_pessoa` INT NOT NULL,
  `banner` VARCHAR(255) NULL,
  `descricao` VARCHAR(1000) NULL,
  `regulamento` VARCHAR(255) NULL,
  `cep` VARCHAR(8) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `logradouro` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(10) NULL,
  `edicao` INT NULL,
  `ativo` TINYINT(1) NULL,
  `organizador_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_corridas_organizadores1_idx` (`organizador_id` ASC),
  CONSTRAINT `fk_corridas_organizadores1`
    FOREIGN KEY (`organizador_id`)
    REFERENCES `SGCR`.`organizador` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGCR`.`lote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGCR`.`lote` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `preco` DOUBLE NOT NULL,
  `data_inicio` VARCHAR(19) NOT NULL,
  `data_final` VARCHAR(19) NOT NULL,
  `corrida_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ingressos_corridas1_idx` (`corrida_id` ASC),
  CONSTRAINT `fk_ingressos_corridas1`
    FOREIGN KEY (`corrida_id`)
    REFERENCES `SGCR`.`corrida` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGCR`.`percurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGCR`.`percurso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `imagem` VARCHAR(255) NULL,
  `quilometragem` DOUBLE NOT NULL,
  `descricao` VARCHAR(1000) NULL,
  `organizador_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_percurso_organizador1_idx` (`organizador_id` ASC),
  CONSTRAINT `fk_percurso_organizador1`
    FOREIGN KEY (`organizador_id`)
    REFERENCES `SGCR`.`organizador` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGCR`.`kit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGCR`.`kit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(200) NULL,
  `imagem` VARCHAR(255) NULL,
  `tipo_chip` VARCHAR(45) NOT NULL,
  `data_inicio_retirada` VARCHAR(10) NOT NULL,
  `data_final_retirada` VARCHAR(10) NOT NULL,
  `organizador_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_kit_organizador1_idx` (`organizador_id` ASC),
  CONSTRAINT `fk_kit_organizador1`
    FOREIGN KEY (`organizador_id`)
    REFERENCES `SGCR`.`organizador` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGCR`.`inscricao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGCR`.`inscricao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `corrida_id` INT NOT NULL,
  `data_compra` VARCHAR(10) NOT NULL,
  `numero_peito` INT NULL,
  `pago` TINYINT(1) NULL,
  `kit_retirado` TINYINT(1) NULL,
  `tempo_largada` VARCHAR(8) NULL,
  `tempo_chegada` VARCHAR(8) NULL,
  `atleta_id` INT NOT NULL,
  `percurso_id` INT NOT NULL,
  `lote_id` INT NOT NULL,
  `kit_id` INT NOT NULL,
  PRIMARY KEY (`id`, `corrida_id`),
  INDEX `fk_inscricao_atleta1_idx` (`atleta_id` ASC),
  INDEX `fk_inscricoes_percursos1_idx` (`percurso_id` ASC),
  INDEX `fk_inscricao_lote1_idx` (`lote_id` ASC),
  INDEX `fk_inscricao_kit1_idx` (`kit_id` ASC),
  INDEX `fk_inscricao_corrida1_idx` (`corrida_id` ASC),
  CONSTRAINT `fk_inscricao_atleta1`
    FOREIGN KEY (`atleta_id`)
    REFERENCES `SGCR`.`atleta` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_inscricoes_percursos1`
    FOREIGN KEY (`percurso_id`)
    REFERENCES `SGCR`.`percurso` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_inscricao_lote1`
    FOREIGN KEY (`lote_id`)
    REFERENCES `SGCR`.`lote` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_inscricao_kit1`
    FOREIGN KEY (`kit_id`)
    REFERENCES `SGCR`.`kit` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_inscricao_corrida1`
    FOREIGN KEY (`corrida_id`)
    REFERENCES `SGCR`.`corrida` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGCR`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGCR`.`administrador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGCR`.`ranking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGCR`.`ranking` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `intervalo_faixa_etaria` INT NULL,
  `idade_inicial` INT NULL,
  `administrador_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rankings_administrador1_idx` (`administrador_id` ASC),
  CONSTRAINT `fk_rankings_administrador1`
    FOREIGN KEY (`administrador_id`)
    REFERENCES `SGCR`.`administrador` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGCR`.`pontuacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGCR`.`pontuacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ranking_id` INT NOT NULL,
  `pontuacao` INT NOT NULL,
  PRIMARY KEY (`id`, `ranking_id`),
  INDEX `fk_pontuacao_ranking1_idx` (`ranking_id` ASC),
  CONSTRAINT `fk_pontuacao_ranking1`
    FOREIGN KEY (`ranking_id`)
    REFERENCES `SGCR`.`ranking` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGCR`.`corrida_ranking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGCR`.`corrida_ranking` (
  `corrida_id` INT NOT NULL,
  `ranking_id` INT NOT NULL,
  INDEX `fk_corrida_ranking_corridas1_idx` (`corrida_id` ASC),
  INDEX `fk_corrida_ranking_rankings1_idx` (`ranking_id` ASC),
  PRIMARY KEY (`corrida_id`, `ranking_id`),
  CONSTRAINT `fk_corrida_ranking_corridas1`
    FOREIGN KEY (`corrida_id`)
    REFERENCES `SGCR`.`corrida` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_corrida_ranking_rankings1`
    FOREIGN KEY (`ranking_id`)
    REFERENCES `SGCR`.`ranking` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGCR`.`boleto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGCR`.`boleto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo_barra` VARCHAR(45) NOT NULL,
  `data_emissao` VARCHAR(10) NOT NULL,
  `data_vencimento` VARCHAR(10) NOT NULL,
  `nome_titular` VARCHAR(45) NOT NULL,
  `cpf_titular` VARCHAR(14) NOT NULL,
  `inscricao_id` INT NOT NULL,
  `inscricao_corrida_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_boleto_inscricao1_idx` (`inscricao_id` ASC, `inscricao_corrida_id` ASC),
  CONSTRAINT `fk_boleto_inscricao1`
    FOREIGN KEY (`inscricao_id` , `inscricao_corrida_id`)
    REFERENCES `SGCR`.`inscricao` (`id` , `corrida_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGCR`.`cartao_credito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGCR`.`cartao_credito` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(16) NOT NULL,
  `codigo_seguranca` VARCHAR(3) NOT NULL,
  `validade` VARCHAR(7) NOT NULL,
  `nome_titular` VARCHAR(45) NOT NULL,
  `inscricao_id` INT NOT NULL,
  `inscricao_corrida_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cartao_credito_inscricao1_idx` (`inscricao_id` ASC, `inscricao_corrida_id` ASC),
  CONSTRAINT `fk_cartao_credito_inscricao1`
    FOREIGN KEY (`inscricao_id` , `inscricao_corrida_id`)
    REFERENCES `SGCR`.`inscricao` (`id` , `corrida_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGCR`.`kit_corrida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGCR`.`kit_corrida` (
  `corrida_id` INT NOT NULL,
  `kit_id` INT NOT NULL,
  `preco` DOUBLE(6,2) NOT NULL,
  PRIMARY KEY (`corrida_id`, `kit_id`),
  INDEX `fk_kit_corrida_kit1_idx` (`kit_id` ASC),
  INDEX `fk_kit_corrida_corrida1_idx` (`corrida_id` ASC),
  CONSTRAINT `fk_kit_corrida_kit1`
    FOREIGN KEY (`kit_id`)
    REFERENCES `SGCR`.`kit` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_kit_corrida_corrida1`
    FOREIGN KEY (`corrida_id`)
    REFERENCES `SGCR`.`corrida` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGCR`.`percurso_corrida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGCR`.`percurso_corrida` (
  `corrida_id` INT NOT NULL,
  `percurso_id` INT NOT NULL,
  PRIMARY KEY (`corrida_id`, `percurso_id`),
  INDEX `fk_percurso_corrida_corrida1_idx` (`corrida_id` ASC),
  CONSTRAINT `fk_percurso_corrida_percurso1`
    FOREIGN KEY (`percurso_id`)
    REFERENCES `SGCR`.`percurso` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_percurso_corrida_corrida1`
    FOREIGN KEY (`corrida_id`)
    REFERENCES `SGCR`.`corrida` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
